// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Notification struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type NotificationInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type Query struct {
}

type Subscription struct {
}
